name: GitHub Actions Demo
on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]
  jobs:
    example-job-1:
      runs-on: ubuntu-latest
      steps:
        - run: echo "The job 1 was triggered"
