name: GitHub Actions Demo
on: 
  push: 
    branches: [main]
jobs:
  example-job-1:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production on branch ${{ github.ref }}"




