name: Environment Variables
on: 
  push: 
    branches: [main]
jobs:
  example-job-1:
    runs-on: ubuntu-latest
    env: 
      DAY_OF_WEEK: Monday 
    steps: 
      - run: echo "Today is ${{ env.DAY_OF_WEEK }}"
      - name: Build and Publish 
        env: 
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
        run: echo "Publishing package $TWINE_USERNAME"

   



